# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Meng' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

	pod 'Moya'
  pod 'SwiftyJSON'
  pod 'SnapKit'
  pod 'RxSwift'
  pod 'RxCocoa'
  # Pods for Meng

  target 'MengTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MengUITests' do
    # Pods for testing
  end

end
